### ISSUE TITLE
Support select docker tag of openjdk/jetty/tomcat version

### ISSUE THREAD

**Issue by zero-88** [GoogleCloudPlatform/runtime-builder-java#89]
Somehow, in latest tag, application cannot work. That's why `appengine-web.xml` should support to select docker image by tag.
For example:
```yaml
runtime_config:  # Optional
 jdk: openjdk8
 server: jetty:9.4-2017-06-05_15_54
```
Son

P/S: Sorry if this ticket is in wrong project.

**Comment by meltsufin** [comment]
Hi @zero-88. Thanks for the issue submission. Can you please clarify what is not working? What is the error message you're seeing?
You're saying `appengine-web.xml`, but your snippet looks like `app.yaml`.

**Comment by zero-88** [comment]
Hi @meltsufin 
Thank for your response. Sorry, my bad, I corrected the description. It's `app.yaml`,
Application in here is my web application, works on jetty 9.3 but not for 9.4. Weird issue. I will submit another ticket for jetty team later.
But I think this issue is understandable, right?

**Comment by meltsufin** [comment]
@zero-88 We currently only support Jetty 9.4. If you want to use an older image, there are several ways of doing so, for example, with `runtime: custom`.
Feel free to post the Jetty issue here as well. We can involve Jetty committers here.

**Comment by zero-88** [comment]
Yes, I see. I can customize dockerfile but it is quite huge effort if I just use specific version. I can contribute code to resolve this case if needed.
I need to investigate more on jetty then will submit issue later. Because, I use `appengine-java-sdk`with jetty 9.3.18.v20170406 in my local, it works. but with latest jetty docker 9.4, it doesn't work on all environments (my local, docker local, GAE)

**Comment by meltsufin** [comment]
Are you using `appengine-web.xml` at all? This would mean you're targetting App Engine Standard (not Flexible), or App Engine Flexible Compat, which has been deprecated.
If you are just writing a vanilla App Engine Flexible Java app, you don't need `appengine-java-sdk`. To run locally, just use the [Jetty Maven Plugin](https://www.eclipse.org/jetty/documentation/9.4.x/jetty-maven-plugin.html).

**Comment by zero-88** [comment]
I just have war file then cannot use any build tool.
I tried on App Engine Standard with `appengine-java-sdk-1.9.58` and itself `jetty 9.3.18.v20170406 ` on my local, then system runs normally.
I used App Engine Flexible with `tomcat:latest` to deploy app, and it works.
I used App Engine Flexible with `jetty:latest` to deploy app, and cannot bring it up on cloud. So weird behavior:
```
Caused by: org.jboss.jca.common.metadata.ParserException: IJ010068: Missing required attribute name in xa-datasource-property
	at org.jboss.jca.common.metadata.AbstractParser.parseConfigProperty(AbstractParser.java:824) ~[?:?]
	at org.jboss.jca.common.metadata.ds.v11.DsParser.parseXADataSource(DsParser.java:150) ~[?:?]
	at org.jboss.jca.common.metadata.ds.v10.DsParser.parseDataSources(DsParser.java:185) ~[?:?]
	at org.jboss.jca.common.metadata.ds.v10.DsParser.parse(DsParser.java:124) ~[?:?]
	at org.jboss.jca.common.metadata.ds.v10.DsParser.parse(DsParser.java:87) ~[?:?]
	at org.jboss.jca.deployers.fungal.DsXmlDeployer.deploy(DsXmlDeployer.java:202) ~[?:?]
	at com.github.fungal.impl.MainDeployerImpl.deploy(MainDeployerImpl.java:170) ~[?:?]
	at com.github.fungal.impl.MainDeployerImpl.deploy(MainDeployerImpl.java:79) ~[?:?]
	at org.jboss.jca.embedded.EmbeddedJCA.deploy(EmbeddedJCA.java:200) ~[?:?]
	at com.thomsonreuters.listener.JcaBootstrapServletContextListener.deployDataSource(JcaBootstrapServletContextListener.java:141) ~[?:?]
	... 38 more
```
I'm finding a different between Jetty 9.3 and 9.4 and building another docker from jetty 9.3.
Anyway, it is out of scope for this ticket.
As user, I would like to switch another server version by configuration. For now, it's impossible except writing Dockerfile. 
It is my expectation, so can we do it? Do you see any side effect on current mechanism?

**Comment by meltsufin** [comment]
You can in fact switch to Tomcat via configuration in `app.yaml`. The reason we don't provide a switch to Jetty 9.3 is because we don't have an officially supported Jetty 9.3 image for App Engine Flexible.

For Tomcat, all you need is your `.WAR` and an `app.yaml` with the following contents:

```yaml
runtime: java
env: flex
runtime_config:
  server: tomcat8
```
